import { useEffect, useState } from 'react';
import './codex-skins.css';

type Skin = {id:string;name:string;background:string;accent:string;appearance:string;opacity:number;blur:number;fontSize:number;focusX:number;focusY:number;favorite:boolean};
type API = {
 GetCodexSkins():Promise<{themes:Skin[]}>; SaveCodexSkin(s:Skin):Promise<void>; DeleteCodexSkin(id:string):Promise<void>;
 SelectCodexSkinBackground():Promise<string>; ImportCodexSkin():Promise<Skin|null>; ExportCodexSkin(s:Skin):Promise<void>;
 ApplyCodexSkin(s:Skin):Promise<string>; RestoreCodexSkin():Promise<string>; LaunchCodexSkinMode():Promise<string>;
};
function api():API { const a=(window as unknown as {go?:{main?:{App?:API}}}).go?.main?.App;if(!a)throw new Error('请在桌面安装版中使用 Codex 换肤');return a; }
export default function CodexSkins({openExternal}:{openExternal:(url:string)=>Promise<unknown>}) {
 const [skins,setSkins]=useState<Skin[]>([]),[selected,setSelected]=useState<Skin|null>(null),[query,setQuery]=useState(''),[favorites,setFavorites]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 async function reload(){const lib=await api().GetCodexSkins();setSkins(lib.themes||[]);setSelected(s=>s || lib.themes?.[0] || null);}
 useEffect(()=>{void reload().catch(e=>setError(String(e)));},[]);
 async function run(task:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await task();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 function patch(p:Partial<Skin>){setSelected(s=>s?{...s,...p}:s);}
 const visible=skins.filter(s=>s.name.toLowerCase().includes(query.toLowerCase())&&(!favorites||s.favorite));
 return <div className="content-stack codex-skins">
  <section className="page-intro"><div><p className="eyebrow">CODEX SKIN STUDIO</p><h2>Codex 皮肤广场</h2><p>为 Codex 桌面端换背景与配色。侧栏、对话和输入框仍是原生控件。</p></div><button className="secondary-button" onClick={()=>void openExternal('https://dreamskin.cc/gallery')}>DreamSkin 社区广场 ↗</button></section>
  <section className="router-card"><h3>第一次换肤</h3><p>先保存工作并完全退出 Codex，再启动换肤模式，选择皮肤后点击应用。只连接本机调试端口，不修改 Codex 安装文件或模型配置。</p><div className="router-actions"><button className="primary-button" disabled={busy} onClick={()=>void run(async()=>setNotice(await api().LaunchCodexSkinMode()))}>启动 Codex 换肤模式</button><button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>setNotice(await api().RestoreCodexSkin()))}>恢复 Codex 默认界面</button><button className="secondary-button" onClick={()=>void openExternal('https://dreamskin.cc/studio')}>社区在线创作 ↗</button></div><p className="field-note">不会强制结束 Codex。Codex 完全退出后皮肤会消失，下次需要再次应用。请勿将调试端口暴露到网络。</p></section>
  <p className="field-note">换肤模式使用独立的 Codex 桌面配置目录，首次可能需要重新登录。Windows 自动启动目前支持官方商店版，macOS 支持 Applications 中的 Codex。</p>
  <div role="status" aria-live="polite">{busy?'正在处理，请稍候…':notice}</div>{error&&<div className="router-error" role="alert">{error}</div>}
  <div className="skin-workspace"><section className="router-card"><h3>本地皮肤广场</h3><div className="skin-toolbar"><input aria-label="搜索 Codex 皮肤" placeholder="搜索皮肤名称" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={favorites} onChange={e=>setFavorites(e.target.checked)}/>只看收藏</label></div><div className="skin-grid">{visible.map(s=><button className={`skin-tile ${selected?.id===s.id?'selected':''}`} key={s.id} disabled={busy} onClick={()=>setSelected({...s})}><img src={s.background} alt=""/><span><i style={{background:s.accent}}/>{s.favorite?'★ ':''}{s.name}</span></button>)}</div>{!visible.length&&<p>暂无匹配皮肤，可导入或另存一套皮肤。</p>}<div className="router-actions"><button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>{const s=await api().ImportCodexSkin();if(s){await reload();setSelected(s);setNotice('已导入本地皮肤库，点击应用后生效。');}})}>导入皮肤 JSON</button></div><p className="field-note">社区主题在 DreamSkin 网站浏览、预览及投稿；社区 ZIP / Safe CSS 需使用原项目客户端，本助手目前支持自有 JSON 皮肤包。</p></section>
  {selected&&<section className="router-card"><h3>预览与编辑</h3><div className="skin-preview" style={{backgroundImage:`url(${selected.background})`,backgroundPosition:`${selected.focusX}% ${selected.focusY}%`,color:selected.appearance==='light'?'#202631':'#f5f7fc',fontSize:selected.fontSize}}><aside style={{background:`rgba(28,32,40,${selected.opacity/100})`,backdropFilter:`blur(${selected.blur}px)`}}>Codex<br/><br/>＋ 新建对话<br/><br/>项目<br/><br/>历史记录</aside><div><small>模拟预览 · 实际效果以 Codex 为准</small><h3>今天想创造什么？</h3><p style={{color:selected.accent}}>让工作空间更像你。</p><div className="skin-composer" style={{borderColor:selected.accent}}>向 Codex 发送消息…</div></div></div>
  <div className="skin-controls"><label>皮肤名称<input value={selected.name} maxLength={60} onChange={e=>patch({name:e.target.value})}/></label><label>外观<select value={selected.appearance} onChange={e=>patch({appearance:e.target.value})}><option value="auto">跟随 Codex</option><option value="dark">深色</option><option value="light">浅色</option></select></label><label>强调色<input type="color" value={selected.accent} onChange={e=>patch({accent:e.target.value})}/></label><label>收藏<input type="checkbox" checked={!!selected.favorite} onChange={e=>patch({favorite:e.target.checked})}/></label>{([{key:'opacity',label:'面板不透明度',min:15,max:100},{key:'blur',label:'背景模糊',min:0,max:30},{key:'fontSize',label:'文字大小',min:12,max:22},{key:'focusX',label:'背景横向焦点',min:0,max:100},{key:'focusY',label:'背景纵向焦点',min:0,max:100}] as const).map(c=><label key={c.key}>{c.label} · {selected[c.key]}<input type="range" min={c.min} max={c.max} value={selected[c.key]} onChange={e=>patch({[c.key]:Number(e.target.value)})}/></label>)}</div>
  <div className="router-actions"><button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>{const background=await api().SelectCodexSkinBackground();if(background)patch({background});})}>更换本地背景</button><button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>{await api().SaveCodexSkin(selected);await reload();setNotice('已保存到皮肤广场。');})}>保存修改</button><button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>{const s={...selected,id:`custom-${Date.now()}`,name:selected.name+' 副本'};await api().SaveCodexSkin(s);await reload();setSelected(s);setNotice('已另存新皮肤。');})}>另存为新皮肤</button><button className="primary-button" disabled={busy} onClick={()=>void run(async()=>setNotice(await api().ApplyCodexSkin(selected)))}>应用到 Codex</button><button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>{await api().ExportCodexSkin(selected);})}>导出</button><button className="secondary-button" disabled={busy} onClick={()=>{if(window.confirm(`删除“${selected.name}”？已导出的文件不受影响。`))void run(async()=>{await api().SaveCodexSkin(selected);await api().DeleteCodexSkin(selected.id);setSelected(null);await reload();setNotice('已从本地库移除。');});}}>删除</button></div></section>}
  </div><p className="field-note">渲染层基于 <a href="https://github.com/Fei-Away/Codex-Dream-Skin" onClick={e=>{e.preventDefault();void openExternal('https://github.com/Fei-Away/Codex-Dream-Skin');}}>Codex Dream Skin</a>（MIT）。非 OpenAI 官方功能；Codex 更新后可能需要重新适配。内置背景为程序生成渐变，无第三方人物素材。</p>
 </div>;
}
