// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function Configure(arg1:main.ConfigurationRequest):Promise<main.ConfigureResult>;

export function FetchModels(arg1:string):Promise<main.ModelResponse>;

export function GetAppInfo():Promise<main.AppInfo>;

export function ListBackups():Promise<Array<main.BackupInfo>>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function PreviewConfiguration(arg1:main.ConfigurationRequest):Promise<main.ConfigurationPreview>;

export function RestoreBackup(arg1:string):Promise<void>;

export function ScanEnvironment():Promise<main.EnvironmentReport>;
