// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function Configure(arg1) {
  return window['go']['main']['App']['Configure'](arg1);
}

export function FetchModels(arg1) {
  return window['go']['main']['App']['FetchModels'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function PreviewConfiguration(arg1) {
  return window['go']['main']['App']['PreviewConfiguration'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function ScanEnvironment() {
  return window['go']['main']['App']['ScanEnvironment']();
}
